### ISSUE TITLE
How to configure MTConnect Agent 2.0 to use TLS and certifcate?

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/cppagent#266]
Hi, 
Our customer needs to secure the connection with MTConnect Agent.
It would be helpful to have a good sample configuration of how to add TLS and certificate to authenticate the client application.

Thanks

**Comment by wsobel** [comment]
I'll add some support to the MTCUP site regarding configuration for TLS, MQTT, and some other new features. 

I'm at a conference this week, so I'll try to get it done but the end of the week.

**Comment by hulinning2** [comment]
Will,
Any progress on this?
Thanks

**Comment by wsobel** [comment]
I have added some documentation to the following page: https://mtcup.org/e/en/Agent-Usage-and-Configuration

**Comment by MRIIOT** [comment]
In a Docker environment you can use https://traefik.io/traefik/ in front of the Agent.

Here is an example with Let's Encrypt, but you can do your own cert.

```
traefik.toml


[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[certificatesResolvers.lets-encrypt.acme]
  email = "admin@domain.com"
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[providers.docker]
  watch = true
  network = "network1"

[providers.file]
  filename = "/etc/traefik/traefik_dynamic.toml"
```

```
traefik_dynamic.toml


[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:abc"
  ]

[http.routers.api]
  rule = "Host(`monitor.domain.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
```

```
compose.yml


version: '3.8'

services:
  agent:
    profiles:
      - base
    ports:
      - '5000/tcp'
    labels:
      - traefik.enable=true
      - traefik.http.routers.agent.rule=Host(`agent.domain.com`)
      - traefik.http.routers.agent.tls=true
      - traefik.http.routers.agent.tls.certresolver=lets-encrypt
      - traefik.port=5000
    networks:
      network1:
        name: network1
```
